{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if (and .Values.server.enterpriseLicense.secretName .Values.server.enterpriseLicense.secretKey) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "consul.fullname" . }}-license
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "100"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "consul.fullname" . }}-license
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: {{ template "consul.name" . }}
        chart: {{ template "consul.chart" . }}
        release: {{ .Release.Name }}
        component: license
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "consul.fullname" . }}-enterprise-license
      {{- if .Values.global.tls.enabled }}
      volumes:
        - name: tls-ca-cert
          secret:
            secretName: {{ template "consul.fullname" . }}-ca-cert
      {{- end }}
      containers:
        - name: apply-enterprise-license
          image: "{{ default .Values.global.image .Values.server.image }}"
          env:
            - name: ENTERPRISE_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.enterpriseLicense.secretName }}
                  key: {{ .Values.server.enterpriseLicense.secretKey }}
            - name: CONSUL_HTTP_ADDR
              {{- if .Values.global.tls.enabled }}
              value: https://{{ template "consul.fullname" . }}-server:8501
              {{- else }}
              value: http://{{ template "consul.fullname" . }}-server:8500
              {{- end }}
            {{- if .Values.global.tls.enabled }}
            - name:  CONSUL_CACERT
              value: /consul/tls/ca/tls.crt
            {{- end}}
            {{- if .Values.global.bootstrapACLs }}
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ template "consul.fullname" . }}-enterprise-license-acl-token"
                  key: "token"
            {{- end}}
          command:
            - "/bin/sh"
            - "-c"
            - |
              log() {
                echo "$(date +%d-%m-%Y" "%H:%M:%S) $@"
              }

              log "Waiting for leader to be elected..."
              while true; do
                OUTPUT=$(curl --silent --show-error --fail \
                  --max-time 2 \
                  {{- if .Values.global.tls.enabled }}
                  --cacert /consul/tls/ca/tls.crt \
                  {{- end }}
                  "$CONSUL_HTTP_ADDR/v1/status/leader" 2>&1)
                CODE=$?
                log "curl $CONSUL_HTTP_ADDR/v1/status/leader: $OUTPUT"

                # Need to check for empty output because if the servers
                # are running but no leader is elected the endpoint
                # will return HTTP 200 but with empty output.
                if [ $CODE -eq 0 ] && [ "$OUTPUT" != '""' ]; then
                  log "Leader elected"
                  break
                fi

                log "Retrying in 2s"
                sleep 2s
              done

              consul license put "${ENTERPRISE_LICENSE}"
          {{- if .Values.global.tls.enabled }}
          volumeMounts:
            - name: tls-ca-cert
              mountPath: /consul/tls/ca
              readOnly: true
          {{- end }}
      {{- if .Values.global.bootstrapACLs }}
      initContainers:
      - name: ent-license-acl-init
        image: {{ .Values.global.imageK8S }}
        command:
          - "/bin/sh"
          - "-ec"
          - |
            consul-k8s acl-init \
              -secret-name="{{ template "consul.fullname" . }}-enterprise-license-acl-token" \
              -k8s-namespace={{ .Release.Namespace }} \
              -init-type="sync"
      {{- end }}
{{- end }}
{{- end }}
